apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: gcr.io/google_containers/hyperkube:v1.2.0-alpha.8
    command:
    - /hyperkube
    - apiserver
    - --etcd-servers=http://10.0.0.10:2379
    - --etcd-servers-overrides=/events#http://10.0.0.11:2379
    - --allow-privileged=true
    - --service-cluster-ip-range=10.0.192.0/18
    - --insecure-bind-address=0.0.0.0
    - --insecure-port=8080
    - --secure-port=0
    - --admission-control=NamespaceLifecycle,LimitRanger,ResourceQuota
    - --runtime-config=extensions/v1beta1/deployments=true,extensions/v1beta1/daemonsets=true
    ports:
    - containerPort: 8080
      hostPort: 8080
      name: local
